In [ ]:
import numpy as np
import cv2 as cv
face_cascade=cv.CascadeClassifier("haarcascade_frontalface_default.xml")
video=cv.VideoCapture(0,cv.CAP_DSHOW)
while True:
    check, frame = video.read()
    print(frame)  # just to see the how numpy array is changing with image
    gray_image = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray_image, scaleFactor=1.05, minNeighbors=5)
    for x, y, w, h in faces:
        frame = cv.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 3)
        print(x,y,w,h)
    resized = cv.resize(frame, (int(frame.shape[1] / 2), int(frame.shape[0] / 2)))
    cv.imshow("Gray", resized)
    key=cv.waitKey(1)
    if key==ord('q'):
        break
video.release()
cv.destroyAllWindows()

[[[ 75  98  89]
  [ 76  99  90]
  [ 76 100  88]
  ...
  [156 155 126]
  [157 156 127]
  [157 156 127]]

 [[ 71  95  88]
  [ 74  98  91]
  [ 77 100  91]
  ...
  [154 154 127]
  [155 155 128]
  [154 154 127]]

 [[ 73  95  88]
  [ 76  98  91]
  [ 77  99  92]
  ...
  [155 155 128]
  [155 155 128]
  [155 155 128]]

 ...

 [[ 78  63  89]
  [ 79  64  90]
  [ 78  66  91]
  ...
  [109 102 104]
  [107 103 104]
  [106 102 103]]

 [[ 78  63  89]
  [ 79  64  90]
  [ 80  65  91]
  ...
  [107 100 102]
  [106  99 101]
  [104  97  99]]

 [[ 77  62  88]
  [ 79  64  90]
  [ 81  65  94]
  ...
  [106  99 101]
  [103  96  98]
  [102  95  97]]]
